version: 2
jobs:
  # install:
  #   docker:
  #     - image: circleci/node:4.8.2
  #   steps:
  #     - checkout
  #     - run: npm install
  lint:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: npm run prettier
      - run: npm run lint
  test-and-build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: npm run test
      - run: npm run build
  deploy:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: npm version patch
      - run: npm publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      # - install
      - lint:
      # requires:
      #   - install
      - test-and-build:
          # requires:
          #   - install
      - deploy:
          requires:
            - lint
            - test-and-build
