version: 2.1
jobs:
  test1:
    docker:
      - image: circleci/node@12.12.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run prettier
            - run: npm run lint
            - run: npm run test
  build:
    docker:
      - image: circleci/node@12.12.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
  publish:
    docker:
      - image: circleci/node@12.12.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm version patch
            - run: npm publish

workflows:
  version: 2.1
  build-and-publish:
    jobs:
      - test1
      - build:
        requires:
          - test1
      - publish:
        requires:
          - build
