version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: npm install
      - run: npm run prettier
      - run: npm run lint
  test-and-build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: npm run test
      - run: npm run build
  publish:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: npm version patch
      - run: npm publish

workflows:
  version: 2
  build-and-publish:
    jobs:
      - lint
      - test-and-build:
          requires:
            - lint
      - publish:
          requires:
            - test-and-build
